pluginManagement {
  repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
  }
}
plugins {
  id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
  }
}
rootProject.name = "EdgeAIDemo"
include ':app'
include ':edge-ai'
include ':edge-agent-api'
include ':edge-agent-core'
include ':edge-agent-adk'
include ':edge-agent-litertlm'
include ':edge-agent-capabilities'
include ':edge-agent-storage-room'
include ':edge-agent-cloud-openai'
